### ISSUE TITLE
Send to Unreal doesn't work on Blender 4.4

### ISSUE THREAD

**Issue by mahreeoocedev01** [poly-hammer/BlenderTools#142]
Addon: - Send to Unreal 
OS: Windows-10-10.0.19045-SP0 64 Bits
Addon Version: Send to Unreal 2.6.3
Blender Version: Blender 4.4.0 RC
Unreal Version: Unreal 5.4.4

Steps to Reproduce the Problem:
This happens in any scene. So, to reproduce, simply try to export a simple cube using Pipelie>Export (I used the "Send to Disk" option, but I'm pretty sure it happens with "Send to Project" option, too).

Error Log:
Python: RuntimeError: could not create instance of WM_OT_send2ue to call callback function 'invoke'.

First of all, thanks to all contributors for the ongoing support of this addon!

I meant to report this earlier, but I wasn't sure it wasn't already in the works.
With Blender 4.4 just around the corner, a number of addons have been broken by api changes. This includes Send to Unreal. The issue seems to be related to the first change in this list:

https://developer.blender.org/docs/release_notes/4.4/python_api/#blender-based-python-classes-construction

Some more info can be found here:

https://docs.blender.org/api/4.4/info_overview.html#construction-destruction

I hope it will help in getting this addon working on Blender 4.4.

**Comment by JoshQuake** [comment]
Thanks for the report and looking into possible causes!

**Comment by eXitus132** [comment]
Will this get a fix? Any news on this?

**Comment by JoshQuake** [comment]
As soon as I can get to it. Currently recovering from surgery. Should be about 2 weeks unless @jack-yao91 can get to it before I can.

**Comment by eXitus132** [comment]
Oh wow sure no hurry - get well soon!!!

**Comment by mahreeoocedev01** [comment]
> Well 4.4 is released now and autoupdated for me from the Microsoft Store ... taking a cursory glance at it [@mahreeoocedev01](https://github.com/mahreeoocedev01) looks like you captured the issue, testing it's a simple fix.
> 
> Go into operators.py in the root addon folder and change this
> 
> ![Image](https://github.com/user-attachments/assets/6d6adfeb-a152-4002-b27d-14d5ba6edafe)
> 
> to this
> 
> ![Image](https://github.com/user-attachments/assets/634d71a0-c64d-4107-9ea1-1764b2650659)
> 
> as described in the Blender docs. Viola! Seems to work fine.
> 
> That'll do as a fix until an official patch comes along


Yep, that did it. I didn't catch any other problems while exporting a few assets.

Thanks for the help!

**Comment by eXitus132** [comment]
This fix didnt work for me i still get this error: 
type object 'SystemLibrary' has no attribute 'get_console_variable_string_value'  File "...\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\send2ue\dependencies\unreal.py", line 1105

**Comment by DanMcLaughlin** [comment]
That looks like a different error.

**Comment by jack-yao91** [comment]
@eXitus132 what is your unreal engine version? `get_console_variable_string_value` this should be in Unreal 5.0+. You could also disable the Send Unreal validation to check the Unreal project settings,, cause this is where that is getting called.

@DanMcLaughlin I can add that change to a PR

**Comment by eXitus132** [comment]
> [@eXitus132](https://github.com/eXitus132) what is your unreal engine version? `get_console_variable_string_value` this should be in Unreal 5.0+. You could also disable the Send Unreal validation to check the Unreal project settings,, cause this is where that is getting called.
> 
> [@DanMcLaughlin](https://github.com/DanMcLaughlin) I can add that change to a PR

Yes it is unreal 5.1!

**Comment by jack-yao91** [comment]
@eXitus132 Ok my mistake, actually looks like 5.2 is the first to have this under SystemLibrary

https://dev.epicgames.com/documentation/en-us/unreal-engine/python-api/search?q=get_console_variable_string_value&application_version=5.2

**Comment by jack-yao91** [comment]
Also, related to this blender 4.4 issue, I made a PR with fix here
https://github.com/poly-hammer/BlenderTools/pull/143

**Comment by Getue** [comment]
While I don't work for Epic and this is a bit of a drive-by comment, I would highly suggest you guys to apply for a MegaGrant if you haven't already, as the submission window is open.

**Comment by JoshQuake** [comment]
is this completed?

@Getue thanks, I'm workin on it :D

**Comment by eXitus132** [comment]
Still not working for me :( also with the workaround to not check for project settings :(

**Comment by JoshQuake** [comment]
@eXitus132 is it the same error when very project settings is unchecked? Because it shouldn't be lol

**Comment by Moonwards** [comment]
The fix isn't working for me. I went so far as to completely uninstall both Blender 4.4 and 4.3, both through the Windows 11 uninstall programs tool, and then manually deleting their folders in the Program Files and AppData \ Roaming folders. Now I've reinstalled 4.4, but it is free of a lot of my add-ons (though some were automatically reinstalled based on my installation of 4.0). Here is a screenshot showing the operators.py folder in VC, opened from its installed location in AppData, beside an open window of Blender 4.4. The Send to Unreal add-on just isn't there. 

![Image](https://github.com/user-attachments/assets/9e014f5d-a515-4894-a86f-cc4d99fd4d0f)

**Comment by JoshQuake** [comment]
@Moonwards delete the addon files in appdata again and install latest release. Should work. if not please create a new issue
